apiVersion: v1
kind: Service
metadata:
  name: jdk-builder
spec:
  selector:
    app: jdk-builder
  ports:
    - name: placeholder
      port: 42
      targetPort: 42
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jdk-builder
spec:
  selector:
    matchLabels:
      app: jdk-builder
  serviceName: jdk-builder
  replicas: 1
  template:
    metadata:
      labels:
        app: jdk-builder
    spec:
      containers:
        - name: main
          image: ghcr.io/guoyk93/acicn/jdk:builder-8-maven-3.6-debian-11
          imagePullPolicy: Always
          command:
            - sleep
            - '3600'
