apiVersion: v1
kind: Service
metadata:
  name: jdk
spec:
  selector:
    app: jdk
  ports:
    - name: placeholder
      port: 42
      targetPort: 42
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jdk
spec:
  selector:
    matchLabels:
      app: jdk
  serviceName: jdk
  replicas: 1
  template:
    metadata:
      labels:
        app: jdk
    spec:
      containers:
        - name: main
          image: ghcr.io/guoyk93/acicn/jdk:17-pagoda
          imagePullPolicy: Always
