apiVersion: v1
kind: Service
metadata:
  name: kafka-28
spec:
  selector:
    app: kafka-28
  ports:
    - name: placeholder
      port: 42
      targetPort: 42
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-28
spec:
  selector:
    matchLabels:
      app: kafka-28
  serviceName: kafka-28
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-28
    spec:
      containers:
        - name: main
          image: ghcr.io/guoyk93/acicn/kafka:2.8
          env:
            - name: KAFKACFG_zookeeper__connect
              value: "zk-36:2181"
          imagePullPolicy: Always
