apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: php
                port:
                  number: 80
            pathType:  Prefix
            path: /
      host: php.oversea.guoyk.net
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: php
spec:
  selector:
    matchLabels:
      app: php
  serviceName: php
  replicas: 1
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: main
          image: ghcr.io/guoyk93/acicn/php:7.4-pagoda
          imagePullPolicy: Always
