apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  selector:
    app: tomcat
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  serviceName: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: main
          image: ghcr.io/guoyk93/acicn/tomcat:9
          imagePullPolicy: Always
